[package]
name = "katana-rpc"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Katana RPC Implementation."

[dependencies]
anyhow = "1.0.40"
blockifier = { git = "https://github.com/starkware-libs/blockifier" }
hex = { version = "0.4.3", default-features = false }
jsonrpsee = { version = "0.16.2", features = ["full"] }
katana-core = { path = "../katana-core" }
serde.workspace = true
serde_json.workspace = true
starknet.workspace = true
starknet_api.workspace = true
thiserror.workspace = true

[dev-dependencies]
assert_matches = "1.5.0"
tokio.workspace = true